version: '3'

services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - 3000:3000
    command: bin/rails s -p 3000 -b '0.0.0.0'
    env_file: docker/.env
    environment:
      MYSQL_HOST: mysql
      SOLR_URL: http://solr:8983/solr/geoblacklight
    depends_on:
      - mysql
      - solr
    volumes:
      - .:/dryad/dashv2

  mysql:
    image: mysql:5
    env_file: docker/.env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  solr:
    build:
      context: docker/solr
      dockerfile: Dockerfile
    ports:
      - 8983:8983
    volumes:
      - solr_data:/opt/solr/server/solr

volumes:
  mysql_data:
  solr_data:
