default: &default
  adapter: mysql2
  host: <%= ENV['MYSQL_HOST'] || "127.0.0.1" %>
  database: <%= ENV['MYSQL_DATABASE'] || "dryad" %>
  password: <%= ENV['MYSQL_ROOT_PASSWORD'] || "" %>
  port: <%= ENV['MYSQL_PORT'] || "3306" %>
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci

development: &DEVELOPMENT
  <<: *default
  username: <%= ENV['MYSQL_USER'] || "dryad" %>
  password: <%= ENV['MYSQL_PASSWORD'] || "" %>

local:
  <<: *default
  username: travis
  password: ""

test:
  <<: *default
  host: localhost
  database: dashv2_test
  username: travis
  password: ""
